"""Validation for the base FHIR R4 subset generated by this project."""

from __future__ import annotations

import re
import uuid
from collections.abc import Mapping, Sequence
from datetime import date, datetime
from typing import Any

from ..observability.errors import RecordProcessingError

FHIR_ID_PATTERN = re.compile(r"^[A-Za-z0-9\-.]{1,64}$")
GENDERS = {"male", "female", "other", "unknown"}
ENCOUNTER_STATUSES = {
    "planned",
    "arrived",
    "triaged",
    "in-progress",
    "onleave",
    "finished",
    "cancelled",
    "entered-in-error",
    "unknown",
}


def _fail(message: str, field: str | None = None) -> None:
    raise RecordProcessingError(
        "FHIR_VALIDATION_FAILED",
        message,
        stage="FHIR_VALIDATION",
        field=field,
    )


def _object(value: Any, field: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        _fail(f"FHIR element '{field}' must be an object.", field)
    return value


def _array(value: Any, field: str, *, nonempty: bool = False) -> Sequence[Any]:
    if isinstance(value, (str, bytes)) or not isinstance(value, Sequence):
        _fail(f"FHIR element '{field}' must be an array.", field)
    if nonempty and not value:
        _fail(f"FHIR element '{field}' must not be empty.", field)
    return value


def _text(value: Any, field: str) -> str:
    if not isinstance(value, str) or not value.strip():
        _fail(f"FHIR element '{field}' must be a non-empty string.", field)
    return value


def _no_nulls(value: Any, path: str = "resource") -> None:
    if value is None:
        _fail(f"FHIR JSON must omit null values at '{path}'.", path)
    if isinstance(value, Mapping):
        for key, child in value.items():
            _no_nulls(child, f"{path}.{key}")
    elif isinstance(value, list):
        for index, child in enumerate(value):
            _no_nulls(child, f"{path}[{index}]")


def _id(resource: Mapping[str, Any]) -> str:
    value = _text(resource.get("id"), "id")
    if not FHIR_ID_PATTERN.fullmatch(value):
        _fail("FHIR id violates the R4 id primitive constraints.", "id")
    return value


def _identifiers(resource: Mapping[str, Any]) -> None:
    for index, value in enumerate(
        _array(resource.get("identifier"), "identifier", nonempty=True)
    ):
        identifier = _object(value, f"identifier[{index}]")
        _text(identifier.get("system"), f"identifier[{index}].system")
        _text(identifier.get("value"), f"identifier[{index}].value")


def _date(value: Any, field: str) -> None:
    text = _text(value, field)
    try:
        date.fromisoformat(text)
    except ValueError:
        _fail(f"FHIR element '{field}' is not an ISO date.", field)


def _date_time(value: Any, field: str) -> None:
    text = _text(value, field)
    try:
        if len(text) == 10:
            date.fromisoformat(text)
        else:
            parsed = datetime.fromisoformat(text.replace("Z", "+00:00"))
            if parsed.tzinfo is None:
                _fail(
                    f"FHIR element '{field}' requires a timezone when time is present.",
                    field,
                )
    except ValueError:
        _fail(f"FHIR element '{field}' is not an ISO dateTime.", field)


def validate_patient(resource: Mapping[str, Any]) -> None:
    _no_nulls(resource)
    if resource.get("resourceType") != "Patient":
        _fail("Expected Patient resourceType.", "resourceType")
    _id(resource)
    _identifiers(resource)
    if not isinstance(resource.get("active"), bool):
        _fail("Patient.active must be a boolean.", "active")
    for index, value in enumerate(_array(resource.get("name"), "name", nonempty=True)):
        name = _object(value, f"name[{index}]")
        _text(name.get("family"), f"name[{index}].family")
        for given_index, given in enumerate(
            _array(name.get("given"), f"name[{index}].given", nonempty=True)
        ):
            _text(given, f"name[{index}].given[{given_index}]")
    if resource.get("gender") not in GENDERS:
        _fail("Patient.gender is outside the R4 required value set.", "gender")
    _date(resource.get("birthDate"), "birthDate")
    for index, value in enumerate(_array(resource.get("address", []), "address")):
        address = _object(value, f"address[{index}]")
        for line_index, line in enumerate(
            _array(address.get("line"), f"address[{index}].line", nonempty=True)
        ):
            _text(line, f"address[{index}].line[{line_index}]")
        for field in ("city", "state", "postalCode"):
            _text(address.get(field), f"address[{index}].{field}")


def validate_encounter(resource: Mapping[str, Any]) -> None:
    _no_nulls(resource)
    if resource.get("resourceType") != "Encounter":
        _fail("Expected Encounter resourceType.", "resourceType")
    _id(resource)
    _identifiers(resource)
    if resource.get("status") not in ENCOUNTER_STATUSES:
        _fail("Encounter.status is outside the R4 required value set.", "status")
    encounter_class = _object(resource.get("class"), "class")
    _text(encounter_class.get("system"), "class.system")
    _text(encounter_class.get("code"), "class.code")
    subject = _object(resource.get("subject"), "subject")
    reference = _text(subject.get("reference"), "subject.reference")
    if not reference.startswith("urn:uuid:"):
        _fail(
            "Bundled Encounter.subject must use the Patient entry's urn:uuid fullUrl.",
            "subject.reference",
        )
    try:
        uuid.UUID(reference.removeprefix("urn:uuid:"))
    except ValueError:
        _fail("Encounter.subject contains an invalid UUID URN.", "subject.reference")
    period = _object(resource.get("period"), "period")
    _date_time(period.get("start"), "period.start")


def validate_resource(resource: Mapping[str, Any]) -> None:
    if resource.get("resourceType") == "Patient":
        validate_patient(resource)
    elif resource.get("resourceType") == "Encounter":
        validate_encounter(resource)
    else:
        _fail("Unsupported FHIR resourceType.", "resourceType")


def validate_collection_bundle(bundle: Mapping[str, Any]) -> None:
    _no_nulls(bundle, "Bundle")
    if bundle.get("resourceType") != "Bundle":
        _fail("Expected Bundle resourceType.", "resourceType")
    _id(bundle)
    if bundle.get("type") != "collection":
        _fail("Offline export Bundle.type must be collection.", "type")
    _date_time(bundle.get("timestamp"), "timestamp")
    full_urls: set[str] = set()
    for index, value in enumerate(_array(bundle.get("entry"), "entry")):
        entry = _object(value, f"entry[{index}]")
        full_url = _text(entry.get("fullUrl"), f"entry[{index}].fullUrl")
        if full_url in full_urls:
            _fail("Bundle fullUrl values must be unique.", f"entry[{index}].fullUrl")
        full_urls.add(full_url)
        if any(key in entry for key in ("request", "response", "search")):
            _fail("Collection entries cannot contain request, response, or search.")
        validate_resource(_object(entry.get("resource"), f"entry[{index}].resource"))
